# Generated by Django 3.2 on 2025-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20250405_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
