# Generated by Django 3.2 on 2025-05-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_submission_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='output',
        ),
    ]
