# Generated by Django 3.2 on 2025-04-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20250405_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicontestrank',
            name='submission_id',
            field=models.CharField(default='', max_length=32),
        ),
    ]
