# Generated by Django 3.2 on 2025-04-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20250405_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicontestrank',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oicontestrank',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
