# Generated by Django 3.2 on 2025-05-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20250406_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='memory',
            new_name='related_error',
        ),
        migrations.RemoveField(
            model_name='oicontestrank',
            name='runtime',
        ),
    ]
