# Generated by Django 3.2 on 2025-05-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20250514_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='related_error',
            new_name='distance',
        ),
    ]
