# Generated by Django 3.2 on 2025-05-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_rename_related_error_oicontestrank_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='distance',
            new_name='clique_weight',
        ),
    ]
