# Generated by Django 3.2 on 2025-05-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_rename_distance_oicontestrank_clique_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='clique_weight',
            new_name='weight',
        ),
    ]
