# Generated by Django 3.2 on 2025-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_rename_clique_weight_oicontestrank_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicontestrank',
            name='penalties',
            field=models.JSONField(default=dict),
        ),
    ]
