# Generated by Django 3.2 on 2025-05-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_oicontestrank_penalties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='penalties',
            new_name='violations',
        ),
    ]
