# Generated by Django 3.2 on 2025-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_rename_penalties_oicontestrank_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicontestrank',
            name='case',
            field=models.IntegerField(default=0),
        ),
    ]
