# Generated by Django 3.2 on 2025-05-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_oicontestrank_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oicontestrank',
            old_name='weight',
            new_name='average_weight',
        ),
    ]
