# Generated by Django 3.2 on 2025-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_rename_weight_oicontestrank_average_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oicontestrank',
            name='average_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
