# Generated by Django 3.2 on 2025-05-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_alter_oicontestrank_average_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oicontestrank',
            name='case',
        ),
    ]
